const treatmentSteps: TreatmentStep[] = [
  {
    id: 1,
    title: "Marking the philtral columns",
    duration: "45s",
    image: "/images/step 1.png",
    video: "/videos/step 1.mov",
    illustration: "/illustrations/step 1.png",
    description: "With gloved hands, use a cosmetic pencil to draw parallel vertical lines along the ridges of the philtrum (the area between the nose and the upper lip). This initial step is crucial to establish the central reference points that will ensure the symmetry of the Cupid's bow.",
    benefits: ["Central reference points", "Guaranteed symmetry", "Precise foundation"],
  },
  {
    id: 2,
    title: "Defining the Cupid's bow",
    duration: "30s",
    image: "/images/step 2.png",
    video: "/videos/step 2.mov",
    illustration: "/illustrations/step 2.png",
    description: "Based on the guidelines drawn in the previous step, draw the 'V' shape of the Cupid's bow. The precision of this step defines the central and most prominent point of the upper lip. Ensure you achieve clean and symmetrical curves.",
    benefits: ["Precise V shape", "Symmetrical curves", "Defined central point"],
  },
  {
    id: 3,
    title: "Tracing the upper lip contour",
    duration: "40s",
    image: "/images/step 3.png",
    video: "/videos/step 3.mov",
    illustration: "/illustrations/step 3.png",
    description: "Continue drawing the upper lip contour starting from the tips of the Cupid's bow to the corners of the lips. Maintain constant pressure on the pencil for a uniform and clear line. This tracing will serve as a precise guide for pigmentation.",
    benefits: ["Uniform line", "Precise guide", "Defined contour"],
  },
  {
    id: 4,
    title: "Tracing the lower lip contour",
    duration: "40s",
    image: "/images/step 4.jpeg",
    illustration: "/illustrations/step 4.png",
    description: "Draw the contour of the lower lip ensuring to create a balanced and harmonious shape relative to the upper lip. The goal is to define a full and symmetrical lip shape that respects the model's morphology.",
    benefits: ["Balanced shape", "Perfect symmetry", "Overall harmony"],
  },
  {
    id: 5,
    title: "Final tracing verification",
    duration: "1min",
    image: "/images/step 5.jpeg",
    illustration: "/illustrations/step 5.png",
    description: "Carefully examine the complete lip contour. Step back to assess the overall symmetry, balance, and proportions. This is the last opportunity to make adjustments with the pencil before starting the pigmentation procedure.",
    benefits: ["Verified symmetry", "Correct proportions", "Possible adjustments"],
  },
  {
    id: 6,
    title: "Unpacking the sterile needle cartridge",
    duration: "15s",
    image: "/images/step 6.png",
    video: "/videos/step 6.mov",
    illustration: "/illustrations/step 6.png",
    description: "Open the packaging of a single-use needle cartridge. It is imperative to verify that the packaging is properly sealed and that the expiration date has not passed. Handling any sterile equipment must always be done with gloves to maintain asepsis.",
    benefits: ["Sterility assured", "Safety guaranteed", "Equipment verified"],
  },
  {
    id: 7,
    title: "Inserting the cartridge into the dermograph",
    duration: "20s",
    image: "/images/step 7.png",
    video: "/videos/step 7.mov",
    illustration: "/illustrations/step 7.png",
    description: "Insert the needle cartridge into the dermograph (the permanent makeup machine). Ensure it is properly locked, usually via a rotation or 'click' mechanism, to guarantee it will not move during the procedure.",
    benefits: ["Secure fixation", "Stability assured", "Mechanism verified"],
  },
  {
    id: 8,
    title: "Adjusting needle protrusion",
    duration: "15s",
    image: "/images/step 8.png",
    video: "/videos/step 8.mov",
    illustration: "/illustrations/step 8.png",
    description: "Adjust the needle depth by turning the adjustment ring on the dermograph. The length of the needle protruding from the cartridge must be adapted to the lip blush technique and the area to be pigmented. Correct adjustment is essential to deposit pigment at the right depth in the dermis.",
    benefits: ["Optimal depth", "Adapted technique", "Precise deposit"],
  },
  {
    id: 9,
    title: "Testing the dermograph and needle movement",
    duration: "20s",
    image: "/images/step 9.jpeg",
    illustration: "/illustrations/step 9.png",
    description: "Turn on the dermograph to verify that the needle moves smoothly and consistently. This quick check ensures the device is functioning properly before loading it with pigment and starting work.",
    benefits: ["Smooth movement", "Operation verified", "Optimal performance"],
  },
  {
    id: 10,
    title: "Loading pigment onto the needle",
    duration: "15s",
    image: "/images/step 10.jpeg",
    illustration: "/illustrations/step 10.png",
    description: "Dip the tip of the cartridge, with the needle moving, into a pigment cup filled with the chosen color. Let the cartridge draw a small amount of pigment. Avoid overloading the cartridge to allow for clean and controlled application.",
    benefits: ["Optimal loading", "Controlled application", "Uniform color"],
  },
  {
    id: 11,
    title: "Lip contour pigmentation",
    duration: "1min 15s",
    image: "/images/step 11.png",
    video: "/videos/step 11.mov",
    illustration: "/illustrations/step 11.png",
    description: "Begin pigmentation by meticulously following the pencil tracing. Hold the dermograph at an angle of approximately 90 degrees relative to the silicone surface. Use your other hand to slightly stretch the synthetic skin, which allows for gentler needle insertion and a sharper line. Advance with a slow and steady movement to create a continuous and well-defined contour line.",
    benefits: ["Precise contour", "Continuous line", "Sharp definition"],
  },
  {
    id: 12,
    title: "Cleaning and reinforcing the contour",
    duration: "1min 50s",
    image: "/images/step 12.png",
    video: "/videos/step 12.mov",
    illustration: "/illustrations/step 12.png",
    description: "After the first pass, gently clean the area with a clean wipe to remove excess pigment and evaluate line saturation. Apply a care solution or secondary anesthetic if necessary. Go over the contour again to reinforce the color and ensure perfect definition before proceeding to filling.",
    benefits: ["Saturation evaluated", "Color reinforced", "Perfect definition"],
  },
  {
    id: 13,
    title: "Checking the pigmented contour",
    duration: "20s",
    image: "/images/step 13.png",
    video: "/videos/step 13.mov",
    illustration: "/illustrations/step 13.png",
    description: "Once the contour is fully pigmented and cleaned, take a moment to evaluate the result. The contour should be sharp, symmetrical, and uniform. This validation step is essential before starting the filling phase (shading).",
    benefits: ["Sharp contour", "Symmetry validated", "Uniformity verified"],
  },
  {
    id: 14,
    title: "Preparing the dermograph for filling",
    duration: "25s",
    image: "/images/step 14.png",
    video: "/videos/step 14.mov",
    illustration: "/illustrations/step 14.png",
    description: "For the filling phase, a new sterile needle cartridge is often required (sometimes with a different configuration than the one used for the contour). Repeat the hygiene steps by opening the sterile packaging and firmly inserting the new cartridge into the dermograph.",
    benefits: ["New cartridge", "Adapted configuration", "Hygiene maintained"],
  },
  {
    id: 15,
    title: "Introduction to pixelization technique (Shading)",
    duration: "30s",
    image: "/images/step 15.png",
    video: "/videos/step 15.mov",
    illustration: "/illustrations/step 15.png",
    description: "Load the new needle with pigment. Begin filling starting from the contour and moving towards the inside of the lip. Use a fast and light pendulum motion to deposit pigment as small dots (pixels). This technique achieves a powdery and natural effect, avoiding an overly opaque appearance.",
    benefits: ["Powdery effect", "Natural appearance", "Pixelized technique"],
  },
  {
    id: 16,
    title: "Lip filling by pixelization",
    duration: "3min 30s",
    image: "/images/step 16.png",
    video: "/videos/step 16.mov",
    illustration: "/illustrations/step 16.png",
    description: "Continue the pixelization movement over the entire lip surface, working in small sections. Overlap your passes to create a homogeneous color without demarcation. The key is consistency of movement and pressure to ensure uniform color saturation.",
    benefits: ["Homogeneous color", "Uniform saturation", "Constant movement"],
  },
  {
    id: 17,
    title: "Precision work on the lip corners",
    duration: "30s",
    image: "/images/step 17.png",
    video: "/videos/step 17.mov",
    illustration: "/illustrations/step 17.png",
    description: "The corners of the lips are delicate areas. Adapt the angle of your dermograph and the orientation of your movements to properly pigment these rounded areas. A good synthetic skin stretching technique is particularly important here for a sharp result.",
    benefits: ["Delicate areas", "Adapted angle", "Sharp result"],
  },
  {
    id: 18,
    title: "Layering for color saturation",
    duration: "3min 30s",
    image: "/images/step 18.png",
    video: "/videos/step 18.mov",
    illustration: "/illustrations/step 18.png",
    description: "Lip blush is built in several layers. After a first complete pass, clean the lip and evaluate the color. Perform additional passes to intensify the color until the desired saturation is achieved. Each layer adds depth and richness to the final result.",
    benefits: ["Multiple layers", "Depth created", "Color richness"],
  },
  {
    id: 19,
    title: "Applying the pigment mask",
    duration: "15s",
    image: "/images/step 19.png",
    video: "/videos/step 19.mov",
    illustration: "/illustrations/step 19.png",
    description: "Once filling is complete, apply a generous layer of pigment over the entire lip surface and leave it on for a few minutes. This 'mask' allows the pigment to penetrate further into the micro-perforations, maximizing color retention.",
    benefits: ["Optimized penetration", "Maximum retention", "Pigment fixation"],
  },
  {
    id: 20,
    title: "Final cleaning and result reveal",
    duration: "20s",
    image: "/images/step 20.png",
    video: "/videos/step 20.mov",
    illustration: "/illustrations/step 20.png",
    description: "After the setting time, gently remove the pigment mask with a clean, damp wipe. This final step reveals the final color and achieved saturation. The result should be a uniform and well-defined lip color.",
    benefits: ["Color revealed", "Final saturation", "Uniform result"],
  },
]