const treatmentSteps: TreatmentStep[] = [
  {
    id: 1,
    title: "Marquage des colonnes philtrales",
    duration: "45s",
    image: "/images/step 1.png",
    video: "/videos/step 1.mov",
    illustration: "/illustrations/step 1.png",
    description: "Avec des mains gantées, utilisez un crayon cosmétique pour dessiner des lignes verticales parallèles le long des crêtes du philtrum (la zone entre le nez et la lèvre supérieure). Cette étape initiale est cruciale pour établir les points de repère centraux qui garantiront la symétrie de l'arc de Cupidon.",
    benefits: ["Points de repère centraux", "Symétrie garantie", "Base précise"],
  },
  {
    id: 2,
    title: "Définition de l'arc de Cupidon",
    duration: "30s",
    image: "/images/step 2.png",
    video: "/videos/step 2.mov",
    illustration: "/illustrations/step 2.png",
    description: "En vous basant sur les lignes directrices tracées à l'étape précédente, dessinez la forme en 'V' de l'arc de Cupidon. La précision de cette étape définit le point central et le plus proéminent de la lèvre supérieure. Assurez-vous d'obtenir des courbes nettes et symétriques.",
    benefits: ["Forme en V précise", "Courbes symétriques", "Point central défini"],
  },
  {
    id: 3,
    title: "Traçage du contour de la lèvre supérieure",
    duration: "40s",
    image: "/images/step 3.png",
    video: "/videos/step 3.mov",
    illustration: "/illustrations/step 3.png",
    description: "Continuez à dessiner le contour de la lèvre supérieure en partant des pointes de l'arc de Cupidon jusqu'aux commissures des lèvres. Maintenez une pression constante sur le crayon pour une ligne uniforme et claire. Ce tracé servira de guide précis pour la pigmentation.",
    benefits: ["Ligne uniforme", "Guide précis", "Contour défini"],
  },
  {
    id: 4,
    title: "Traçage du contour de la lèvre inférieure",
    duration: "40s",
    image: "/images/step 4.jpeg",
    illustration: "/illustrations/step 4.png",
    description: "Dessinez le contour de la lèvre inférieure en veillant à créer une forme équilibrée et harmonieuse par rapport à la lèvre supérieure. L'objectif est de définir une forme de lèvres pleine et symétrique qui respecte la morphologie du mannequin.",
    benefits: ["Forme équilibrée", "Symétrie parfaite", "Harmonie générale"],
  },
  {
    id: 5,
    title: "Vérification du tracé final",
    duration: "1min",
    image: "/images/step 5.jpeg",
    illustration: "/illustrations/step 5.png",
    description: "Examinez attentivement le contour complet des lèvres. Prenez du recul pour évaluer la symétrie générale, l'équilibre et les proportions. C'est la dernière opportunité de faire des ajustements au crayon avant de commencer la procédure de pigmentation.",
    benefits: ["Symétrie vérifiée", "Proportions correctes", "Ajustements possibles"],
  },
  {
    id: 6,
    title: "Déballage de la cartouche d'aiguille stérile",
    duration: "15s",
    image: "/images/step 6.png",
    video: "/videos/step 6.mov",
    illustration: "/illustrations/step 6.png",
    description: "Ouvrez l'emballage d'une cartouche d'aiguille à usage unique. Il est impératif de vérifier que l'emballage est bien scellé et que la date de péremption n'est pas dépassée. La manipulation de tout équipement stérile doit toujours se faire avec des gants pour maintenir l'asepsie.",
    benefits: ["Stérilité assurée", "Sécurité garantie", "Équipement vérifié"],
  },
  {
    id: 7,
    title: "Insertion de la cartouche dans le dermographe",
    duration: "20s",
    image: "/images/step 7.png",
    video: "/videos/step 7.mov",
    illustration: "/illustrations/step 7.png",
    description: "Insérez la cartouche d'aiguille dans le dermographe (la machine de maquillage permanent). Assurez-vous qu'elle est correctement enclenchée, généralement par un mécanisme de rotation ou de 'clic', pour garantir qu'elle ne bougera pas pendant la procédure.",
    benefits: ["Fixation sécurisée", "Stabilité assurée", "Mécanisme vérifié"],
  },
  {
    id: 8,
    title: "Ajustement de la sortie de l'aiguille",
    duration: "15s",
    image: "/images/step 8.png",
    video: "/videos/step 8.mov",
    illustration: "/illustrations/step 8.png",
    description: "Réglez la profondeur de l'aiguille en tournant la bague d'ajustement du dermographe. La longueur de l'aiguille qui sort de la cartouche doit être adaptée à la technique de lip blush et à la zone à pigmenter. Un réglage correct est essentiel pour déposer le pigment à la bonne profondeur dans le derme.",
    benefits: ["Profondeur optimale", "Technique adaptée", "Dépôt précis"],
  },
  {
    id: 9,
    title: "Test du dermographe et du mouvement de l'aiguille",
    duration: "20s",
    image: "/images/step 9.jpeg",
    illustration: "/illustrations/step 9.png",
    description: "Allumez le dermographe pour vérifier que l'aiguille se déplace de manière fluide et constante. Cette vérification rapide permet de s'assurer que l'appareil fonctionne correctement avant de le charger en pigment et de commencer à travailler.",
    benefits: ["Mouvement fluide", "Fonctionnement vérifié", "Performance optimale"],
  },
  {
    id: 10,
    title: "Chargement du pigment sur l'aiguille",
    duration: "15s",
    image: "/images/step 10.jpeg",
    illustration: "/illustrations/step 10.png",
    description: "Trempez la pointe de la cartouche, avec l'aiguille en mouvement, dans une bague à pigment remplie de la couleur choisie. Laissez la cartouche aspirer une petite quantité de pigment. Évitez de surcharger la cartouche pour permettre une application propre et contrôlée.",
    benefits: ["Chargement optimal", "Application contrôlée", "Couleur uniforme"],
  },
  {
    id: 11,
    title: "Pigmentation du contour des lèvres",
    duration: "1min 15s",
    image: "/images/step 11.png",
    video: "/videos/step 11.mov",
    illustration: "/illustrations/step 11.png",
    description: "Commencez la pigmentation en suivant méticuleusement le tracé au crayon. Tenez le dermographe à un angle d'environ 90 degrés par rapport à la surface du silicone. Utilisez votre autre main pour étirer légèrement la peau synthétique, ce qui permet une insertion plus douce de l'aiguille et une ligne plus nette. Avancez avec un mouvement lent et régulier pour créer une ligne de contour continue et bien définie.",
    benefits: ["Contour précis", "Ligne continue", "Définition nette"],
  },
  {
    id: 12,
    title: "Nettoyage et renforcement du contour",
    duration: "1min 50s",
    image: "/images/step 12.png",
    video: "/videos/step 12.mov",
    illustration: "/illustrations/step 12.png",
    description: "Après le premier passage, nettoyez délicatement la zone avec une lingette propre pour enlever l'excès de pigment et évaluer la saturation de la ligne. Appliquez une solution de soin ou un anesthésiant secondaire si nécessaire. Repassez sur le contour pour renforcer la couleur et assurer une définition parfaite avant de procéder au remplissage.",
    benefits: ["Saturation évaluée", "Couleur renforcée", "Définition parfaite"],
  },
  {
    id: 13,
    title: "Vérification du contour pigmenté",
    duration: "20s",
    image: "/images/step 13.png",
    video: "/videos/step 13.mov",
    illustration: "/illustrations/step 13.png",
    description: "Une fois le contour entièrement pigmenté et nettoyé, prenez un moment pour évaluer le résultat. Le contour doit être net, symétrique et uniforme. Cette étape de validation est essentielle avant de commencer la phase de remplissage (shading).",
    benefits: ["Contour net", "Symétrie validée", "Uniformité vérifiée"],
  },
  {
    id: 14,
    title: "Préparation du dermographe pour le remplissage",
    duration: "25s",
    image: "/images/step 14.png",
    video: "/videos/step 14.mov",
    illustration: "/illustrations/step 14.png",
    description: "Pour la phase de remplissage, une nouvelle cartouche d'aiguille stérile est souvent nécessaire (parfois d'une configuration différente de celle utilisée pour le contour). Répétez les étapes d'hygiène en ouvrant l'emballage stérile et en insérant fermement la nouvelle cartouche dans le dermographe.",
    benefits: ["Nouvelle cartouche", "Configuration adaptée", "Hygiène maintenue"],
  },
  {
    id: 15,
    title: "Initiation à la technique de pixellisation (Shading)",
    duration: "30s",
    image: "/images/step 15.png",
    video: "/videos/step 15.mov",
    illustration: "/illustrations/step 15.png",
    description: "Chargez la nouvelle aiguille en pigment. Commencez le remplissage en partant du contour et en allant vers l'intérieur de la lèvre. Utilisez un mouvement de balancier rapide et léger (pendulaire) pour déposer le pigment sous forme de petits points (pixels). Cette technique permet d'obtenir un effet poudré et naturel, évitant ainsi un aspect trop opaque.",
    benefits: ["Effet poudré", "Aspect naturel", "Technique pixellisée"],
  },
  {
    id: 16,
    title: "Remplissage de la lèvre par pixellisation",
    duration: "3min 30s",
    image: "/images/step 16.png",
    video: "/videos/step 16.mov",
    illustration: "/illustrations/step 16.png",
    description: "Continuez le mouvement de pixellisation sur toute la surface de la lèvre, en travaillant par petites sections. Superposez vos passages pour créer une couleur homogène et sans démarcation. La clé est la consistance du mouvement et de la pression pour garantir une saturation uniforme de la couleur.",
    benefits: ["Couleur homogène", "Saturation uniforme", "Mouvement constant"],
  },
  {
    id: 17,
    title: "Travail de précision sur les commissures",
    duration: "30s",
    image: "/images/step 17.png",
    video: "/videos/step 17.mov",
    illustration: "/illustrations/step 17.png",
    description: "Les commissures des lèvres sont des zones délicates. Adaptez l'angle de votre dermographe et l'orientation de vos mouvements pour pigmenter correctement ces zones arrondies. Une bonne technique d'étirement de la peau synthétique est particulièrement importante ici pour un résultat net.",
    benefits: ["Zones délicates", "Angle adapté", "Résultat net"],
  },
  {
    id: 18,
    title: "Superposition des couches pour la saturation de la couleur",
    duration: "3min 30s",
    image: "/images/step 18.png",
    video: "/videos/step 18.mov",
    illustration: "/illustrations/step 18.png",
    description: "Le lip blush se construit en plusieurs couches. Après un premier passage complet, nettoyez la lèvre et évaluez la couleur. Effectuez des passages supplémentaires pour intensifier la couleur jusqu'à obtenir la saturation désirée. Chaque couche ajoute de la profondeur et de la richesse au résultat final.",
    benefits: ["Couches multiples", "Profondeur créée", "Richesse de couleur"],
  },
  {
    id: 19,
    title: "Application du masque de pigment",
    duration: "15s",
    image: "/images/step 19.png",
    video: "/videos/step 19.mov",
    illustration: "/illustrations/step 19.png",
    description: "Une fois le remplissage terminé, appliquez une couche généreuse de pigment sur toute la surface des lèvres et laissez poser quelques minutes. Ce 'masque' permet au pigment de pénétrer davantage dans les micro-perforations, maximisant ainsi la rétention de la couleur.",
    benefits: ["Pénétration optimisée", "Rétention maximale", "Fixation du pigment"],
  },
  {
    id: 20,
    title: "Nettoyage final et révélation du résultat",
    duration: "20s",
    image: "/images/step 20.png",
    video: "/videos/step 20.mov",
    illustration: "/illustrations/step 20.png",
    description: "Après le temps de pose, retirez délicatement le masque de pigment avec une lingette propre et humide. Cette dernière étape révèle la couleur finale et la saturation obtenue. Le résultat doit être une couleur de lèvres uniforme et bien définie.",
    benefits: ["Couleur révélée", "Saturation finale", "Résultat uniforme"],
  },
  {
    id: 21,
    title: "Nettoyage approfondi de la zone de travail",
    duration: "30s",
    image: "/images/step 21.png",
    video: "/videos/step 21.mov",
    illustration: "/illustrations/step 21.png",
    description: "Utilisez une lingette propre, potentiellement imbibée d'une solution nettoyante douce, pour essuyer soigneusement toute la zone autour des lèvres. L'objectif est d'éliminer toute trace de pigment sur la peau en silicone afin d'isoler visuellement le travail effectué et d'apprécier la netteté du contour. Un travail propre est le reflet du professionnalisme.",
    benefits: ["Zone propre", "Contour isolé", "Professionnalisme"],
  },
  {
    id: 22,
    title: "Présentation finale du travail",
    duration: "20s",
    image: "/images/step 22.png",
    video: "/videos/step 22.mov",
    illustration: "/illustrations/step 22.png",
    description: "Effectuez un dernier passage délicat avec une lingette propre pour parfaire le nettoyage et vous assurer que la surface est impeccable. Cette étape finale met en valeur le résultat, en s'assurant qu'aucune particule ou résidu ne vienne distraire l'œil. Le travail est maintenant prêt à être photographié pour votre portfolio ou présenté pour évaluation.",
    benefits: ["Surface impeccable", "Résultat valorisé", "Prêt pour évaluation"],
  },
]